[build]
  command = "(test -d flutter_sdk && git -C flutter_sdk pull || git clone https://github.com/flutter/flutter.git -b stable --depth 1 flutter_sdk) && export PATH=\"$PATH:$PWD/flutter_sdk/bin\" && flutter config --enable-web && flutter pub get && flutter build web --release --dart-define=SENTRY_DSN=$SENTRY_DSN --dart-define=API_BASE_URL=$API_BASE_URL --dart-define=CAPSULE_PRICE=$CAPSULE_PRICE --dart-define=YANDEX_GEOCODER_KEY=$YANDEX_GEOCODER_KEY"
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
